services:
  - type: web
    name: btc-predictor-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.10
    region: oregon
